### ISSUE TITLE
getPointAtLength() performance

### ISSUE THREAD

**Issue by adrianmiu** [adobe-webplatform/Snap.svg#109]
I've used Raphael for a project and we're considering moving to snapsvg. 
The app uses getPointAtLength() to determine the optimal point where a line should end on a path. For big paths there are a lot of getPointAtLength() calls.

We've done some benchmarks on the performance of this function (on a circle's realPath attribute) and SnapSVG is almost 2 times slower.

On the other hand getTotalLength() is about 4 time faster.

**Comment by sfentress** [comment]
For `attr()`, I opened up another ticket, with another jsPerf: #544
