### ISSUE TITLE
Access <tspan> elements?

### ISSUE THREAD

**Issue by Siyfion** [adobe-webplatform/Snap.svg#113]
When you use the method `paper.text(0, 0, ["Some", "example", "text"]);` I can't seem to find a way to get an `Element` handle on any of the `<tspan>` elements...

What if I want to use that method and then manually adjust the `dy` and `dx` values for each? I'd almost like to be able to do something like:

``` javascript
textElement = paper.text(0, 0, ["Some", "example", "text"]);
textElement.tspans[0].attr({ dy: '1em' });
```

**Comment by happystory** [comment]
> @DmitryBaranovskiy Could I recommend this little snippet is added to the documentation for the `paper.text` method?

I couldn't agree more.

**Comment by ralienpp** [comment]
Hello from 2022! I agree with the suggestion to add that snippet to the documentation.


I've been looking around the web, and this Github issue (which is useful) is buried under other pages, which suggest other approaches. Before stumbling upon this discussion, I was leaning towards a variation of this (i.e., manually build the string and parse it):

```
//method 3, simply 'parse' the relevant text you want to add
var frag = Snap.parse('<text x="40" y="90" style="font-size:40px id="text3340">1<tspan style="font-size:20px;baseline-shift:super;" id="tspan3344">3</tspan><tspan id="tspan3352" style="font-size:22.5px">4</tspan></tspan></text>')
s.append(frag)
```

**Comment by ibrierley** [comment]
There's a few different ways to do it! Both of those should be fine.
