### ISSUE TITLE
Missing toFront() / .toBack() 

### ISSUE THREAD

**Issue by oslego** [adobe-webplatform/Snap.svg#121]
element.toFront(), element.toBack() and paper.top from Raphael have no obvious correspondent in Snap.

They are useful util methods. An workaround with attr() and z-index may work, but built-in methods to handle this would be very welcome.

**Comment by vlalieu** [comment]
thanks Dimitry, your method works!

**Comment by olibou** [comment]
Hi!
I've tried toFront and toBack and it did not work for me. Below is my minimal example where I would like that when cursor is going over a box it scales it and brings it to the front. Any idea ?

    var s = Snap('#test');
    var  g = s.g(s.rect(50,50,150,50).attr({fill:'blue'}),
		 s.text(75,80, 'Hello World'));
    g.hover(enter_box, leave_box);
    
    var  g = s.g(s.rect(70,60,150,60).attr({fill:'green'}),
		 s.text(80,90, 'How good is Snap!'));
    g.hover(enter_box, leave_box);
    function enter_box() {
	var bbr = this.getBBox();
	this.animate({transform: (new Snap.Matrix()).scale(2, 2, bbr.cx, bbr.cy)}, 100);
    }
    function leave_box() {
	this.animate({transform: 's1'},100); 
    }

**Comment by pp19dd** [comment]
Decade late here, but remixing Dmitry's answer to account for groups.  If an element is already in a group, it should be sent to back / front only in its group, not broken out into the svg.

    Snap.plugin(function (Snap, Element, Paper, glob) {
        var elproto = Element.prototype;
        elproto.toFront = function() {
            if( this.parent().type == "g" ) {
                this.appendTo(this.parent());
            } else {
                this.appendTo(this.paper);
            }
            return( this );
        };
        elproto.toBack = function() {
            if( this.parent().type == "g" ) {
                this.prependTo(this.parent());
            } else {
                this.prependTo(this.paper);
            }
            return( this );
        };
    });
