### ISSUE TITLE
Snap.parse in IE 10 returns fragment without it's innerSVG 

### ISSUE THREAD

**Issue by dabedur** [adobe-webplatform/Snap.svg#196]
The last step in the Snap.parse function before it returns a new fragment is to set the innerHTML of the temporary div to an empty string. For reasons unknown to me, IE keeps the reference to this temporary div which results in a returned fragment without the child elements of the string you passed in to parse.

Commenting out "div.innerHTML = E" (line 3148 in version 0.2.0) resolves the issue, however I'm unsure of the repercussions, if any.

**Comment by zetta83** [comment]
This fix dont work in IE11

**Comment by ibrierley** [comment]
Can you post a jsfiddle.

**Comment by zetta83** [comment]
http://jsfiddle.net/zetta/y9uq0L9w/

**Comment by petermatik** [comment]
Simple fix in Snap.parse func:

```javascript
if (svg) {
    if (full) {
        //ORIG (IE Err)
        //f = svg;
        //NEW
        while (div.childNodes[0]) {
	        f.appendChild(div.childNodes[0]);
	    }
    } else {
        while (svg.firstChild) {
            f.appendChild(svg.firstChild);
        }
    }
}
```
