### ISSUE TITLE
Globe Animation Demo Broken in Firefox

### ISSUE THREAD

**Issue by joshbroton** [adobe-webplatform/Snap.svg#236]
The latest update to Firefox has broken your Globe Animation Demo. I've used a similar animation on http://lemonly.com/canon/global-counterfeit-supply-chain/ which works great in every browser but Firefox.

I've included a screenshot of what it looks like. I have absolutely no idea how to fix it. :(

![screen shot 2014-04-30 at 11 18 56 am](https://cloud.githubusercontent.com/assets/763668/2843794/40999458-d083-11e3-99e1-6dd1eabdda0c.png)

**Comment by longsonr** [comment]
This was fixed in Firefox some time ago. The testcase works fine now.
