### ISSUE TITLE
Snap.path.isPointInside() error

### ISSUE THREAD

**Issue by showdep** [adobe-webplatform/Snap.svg#248]
Run the following code in jsFiddle (i tried it in versions 0.1.0 and 0.2.0). isPointInside must return true, but it returns false. For rounded coordinates, it works good. Found this by coincidence.

var s = Snap(640,480);
var p = "M1.4315332974182866,4.405806462382467 L57.26133189673147,176.23225849529868 A185.30156250000002,185.30156250000002 0 0 1 -172.2890356108522,-68.21405480708441 L-4.307225890271305,-1.7053513701771101 A4.6325390625,4.6325390625 0 0 0 1.4315332974182866,4.405806462382467 Z";
var x = -58.296875, y=70.96875;

// It works ok for rounded coordinates though
//var x = -58.3, y=71;

s.g(
  s.path(p).attr("fill","#A00000"),
  s.circle(x,y,4).attr("fill","#000000")
).transform("t200,200");

alert("You can see the circle IS in path, but isPointInside returns : " + Snap.path.isPointInside(p, x,y).toString());

**Comment by emoyaferrada** [comment]
Updated fix for #248, same error here using closed paths transformed from shapefiles polygons, Snap.path.isPointInside() function is not working at all. 

Please see jsfiddle in:
http://jsfiddle.net/ouuou1my/  

Thanks.
