### ISSUE TITLE
Undefined when drawing circle from example

### ISSUE THREAD

**Issue by igorrKurr** [adobe-webplatform/Snap.svg#320]
I tried to execute example code from site, but this error appears, when calling `circle` function:
http://joxi.ru/p27OGO3tojPd27

**Comment by bseib** [comment]
I fell into the same trap when trying out snap.svg the very first time. Here's what I was reading:

![image](https://cloud.githubusercontent.com/assets/1313561/12381584/e5fec74a-bd5a-11e5-94b9-fc063d36308b.png)

It should read "<svg> element" rather the "SVG element", and it would have been crystal clear what was needed. Somehow my brain forgot that svg stuff had it's own tag.
