### ISSUE TITLE
Update snapsvg npm package

### ISSUE THREAD

**Issue by mikemaccana** [adobe-webplatform/Snap.svg#337]
The current 'snapsvg' package on npm uses a Gruntfile as its main, so simply importing the module results in a massive amount of unnecessary compilation.

snapsvg should be owned by snapsvg, just like jquery is owned by jquery.

**Comment by milotoor** [comment]
:+1:

Would really appreciate publishing this. I am currently using browserify for my build, and I'm not able to `require('snapsvg')` without the package.json being updated.

**Comment by mikemaccana** [comment]
Milotoor try npm install from github. Then use shrink wrap to lock the version till they publish a permanent fix.
