### ISSUE TITLE
Snap.select('#query') is returning a Null value even though the SVG is loaded.

### ISSUE THREAD

**Issue by zubairanwar2** [adobe-webplatform/Snap.svg#345]
It does not happen all the time though, after lets say 3 or 4 times refreshing the problem does not persist in Chrome/FF/Opera but IE gets stuck there and does not run the code even after multiple refreshing. So is there something I am doing wrong here ? and one other thing I noticed was that some RegEx in Snapsvg.js which has '[.../*]', the code after this is commented, I use DreamWeaver they all are commented which is not supposed to be actually. Is it normal behaviour ,will browsers ignore this part. I am sorry it is a bit out of topic but it might be due to this the Snap.select('#query') is returning a Null. Please give me some insight about it. Thanks.

**Comment by ibrierley** [comment]
Can you put an example on a jsfiddle ?

**Comment by zubairanwar2** [comment]
I am sorry for asking such a silly question actually, everything was working normal after I changed from $(document).ready() to window.onload.. So now I found that the SVG was not fully loaded, this question is so silly now that I read it. I apologize.
