### ISSUE TITLE
Marker not inserted after removing svg and adding new one

### ISSUE THREAD

**Issue by wmalevski** [adobe-webplatform/Snap.svg#346]
Hello, 

I have very strange situation, I need to re-create the whole SVG, when a user clicks on a button, so I need to destroy the previous one (snapHolder.remove() ) and I add in the DOM new <svg id="svg"> which I insert with jQuery. Then I'm creating a new instance of the snap (snapHolder = new Snap("#svg")). Everything works well, without markers. They are simply not added in the SVG. 

I think it's Snap SVG related issue, because it's the snap which insert them into the DOM. when I check my logic and make some console logs, I see that the element is created exactly the same way, like the first time, but it's just not appearing into my SVG:

Element_: Objectanims: Objectid: "Si5qwy2hj3t"node: marker#Si5qwy2hj3tpaper: Elementtype: "marker"__proto__: Element

I also, see that the line I'm attaching the marker, is containing the marker:

<line x1="660" x2="693" y1="872" y2="872" stroke="#000000" style="stroke-width: 2px; marker-end: url(#Si5qwy2hj3t);"></line>

Just the marker it's not presented into the SVG.

Thanks in advance!

**Comment by ibrierley** [comment]
As ever, an example fiddle or something would help :).

**Comment by wmalevski** [comment]
Hello, 

I have made the fiddle and then it was working! So I started to check and just replaced my snap.svg.js with the latest one and it works fine. Thanks!

Here is the fiddle:

http://jsfiddle.net/0LedLacq/

Locally I'm with Snap v 0.0.1
After update I'm using: v 0.3.0
