### ISSUE TITLE
So how do you create a Set?

### ISSUE THREAD

**Issue by Jakobud** [adobe-webplatform/Snap.svg#348]
Seems like I must be missing something here. I don't see anything in the documentation on how to actually create a Set. I see only methods for acting on sets.

**Comment by ibrierley** [comment]
Try 
var mySet = Snap.set();
mySet.push( mySvgElement );

**Comment by Jakobud** [comment]
Oh that worked thanks. How come this isn't documented? Seems like a primary aspect of Snap.svg and it's completely ignored in the docs...
