### ISSUE TITLE
Z Order

### ISSUE THREAD

**Issue by seemsindie** [adobe-webplatform/Snap.svg#354]
Hello guys,

I have a question about z order, how do i move one element behind another and vice versa?

I looked ad #121 but when i implemented that code, my element would dispersers if i tried any of those two methods.
Any ideas?

Thanks, Ivan.

**Comment by ian-workcircle** [comment]
Try adding it higher in the DOM, so maybe you can use before/insertBefore/after/insertAfter, or a simple add/append will readd the element again so it would appear 'higher'. Post a basic example on a jsfiddle if still not working.

**Comment by ibrierley** [comment]
Try adding it higher in the DOM, so maybe you can use before/insertBefore/after/insertAfter, or a simple add/append will readd the element again so it would appear 'higher'. Post a basic example on a jsfiddle if still not working.

**Comment by seemsindie** [comment]
Ok i have this demo http://plnkr.co/edit/ZOzGnYUqcPgIoMDnWfgM?p=preview
And i would like to be able to switch two layers(hexagons and the actual map), or when i move hexagons that hexagon to be always on top, but when i use toFront and toBack the element just dispersers.
Any ideas?

**Comment by ibrierley** [comment]
What I'm guessing there, is that you are adding it outside of the svg thats styling it etc. So rather than add it to the paper, you probably want to add it to layer1 for example, so you could do something like 

elproto.toFront = function () {
         Snap('#layer1').add( this );
       };

or just store a select of #layer1 and use that as a reference is possibly better.

**Comment by seemsindie** [comment]
@ibrierley Thanks man, that did the trick.
