### ISSUE TITLE
Ignore a text node on hover

### ISSUE THREAD

**Issue by smockensturm** [adobe-webplatform/Snap.svg#356]
I have a simple path morphing into (and out of) another simple path when hovering over said path. Trouble is, when I hover over a text node that is on top of said path, the hover out handler fires. Undesirable.

Any way to ignore a text node when hovering over a path?

**Comment by ibrierley** [comment]
Maybe try 'pointer-events: none' as css for the text element.

**Comment by smockensturm** [comment]
Nice. Looks good. Thanks!
