### ISSUE TITLE
Get Started page contains JavaScript error at 9 step  http://snapsvg.io/start/ 

### ISSUE THREAD

**Issue by rayqian** [adobe-webplatform/Snap.svg#363]
Chrome and Safari both have this issue. 

Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': 'circle\:nth-child(2)' is not a valid selector.snap.svg-min.js:19 d.plugin.m.selectVM893:31 (anonymous function)(index):124 callback(index):137 (anonymous function)snap.svg-min.js:19 msnap.svg-min.js:19 m.fsnap.svg-min.js:21 d.plugin.f

**Comment by yehiasalam** [comment]
yup i would say its a critical issue
