### ISSUE TITLE
Failed to execute 'querySelector' on 'Element': 'tspan\:nth-child(1)' is not a valid selector

### ISSUE THREAD

**Issue by skyrack2** [adobe-webplatform/Snap.svg#365]
snap.svg.js:3057 Uncaught SyntaxError: Failed to execute 'querySelector' on 'Element': 'tspan\:nth-child(1)' is not a valid selector.

same with minified too.

This was running the clock in the demos folder.

**Comment by ibrierley** [comment]
Doesn't give that error for me, can you produce a jsfiddle for it ? Also mention which browser, as sometimes those errors are basically browser errors, rather than snap as such.

**Comment by skyrack2** [comment]
Well I just downloaded Snap with the Clock in Demos and am using Chrome.
Did you use the download?

**Comment by ibrierley** [comment]
http://svg.dabbles.info/clockdemo.html works fine for me (Chrome).

**Comment by skyrack2** [comment]
Well you are using Snap 0.3.0....
I have downloaded 0.4.0

**Comment by ibrierley** [comment]
Ah fair enough, thats why a fiddle helps :).  Yes it looks like 0.4 is
doing something odd there, adding an extra slash before the colon maybe.

**Comment by ibrierley** [comment]
In fact if line 3056 is commented out in Snap, it works fine. I'm not sure what that regex is there for, so not sure what the correct regex should be for a fix...

query = Str(query).replace(/([^\\]):/g, "$1\\:");

**Comment by skyrack2** [comment]
in which version?

that does not work for me in 0.4.0
line 3057 gives the error

**Comment by ibrierley** [comment]
See if these work differently to you...

http://svg.dabbles.info/clockdemo.html (0.4)
http://svg.dabbles.info/clockdemo_fix.html (0.4 using Snap with regex
commented out).

Line 3057 gives an error as the previous line has changed the query, I'm
not sure what this is for (it wasn't there in 0.3), so leaving it out may
break something else, but hopefully Dmitry may spot whats the actual
intention and produce a fix.

Ian

**Comment by skyrack2** [comment]
Yes the latter with the amended code works for me now.
I will use your 0.4.amended.js for now.

I have downloaded the amended and that works locally for me too.

If and when there is a fix will that be a new version number?

Thanks
