### ISSUE TITLE
Element.animate does not accept with an instance of Animation (created through Snap.animation)

### ISSUE THREAD

**Issue by Pickachu** [adobe-webplatform/Snap.svg#366]
I don't know if is just a typo, but changing ms = easing.dur; to ms = attrs.dur;, solves the bug.

Reproducible Fiddle
http://jsfiddle.net/p1qoo0yk/

Possible error location:
https://github.com/adobe-webplatform/Snap.svg/blob/master/src/element.js#L801
```javascript
    elproto.animate = function (attrs, ms, easing, callback) {
        if (typeof easing == "function" && !easing.length) {
            callback = easing;
            easing = mina.linear;
        }
        if (attrs instanceof Animation) {
            callback = attrs.callback;
            easing = attrs.easing;
            ms = easing.dur;
            attrs = attrs.attr;
        }
```

**Comment by ibrierley** [comment]
I'm guessing this may be related to https://github.com/adobe-webplatform/Snap.svg/pull/180

**Comment by Pickachu** [comment]
Yep, its a duplicate. Didn't find it on search though.
