### ISSUE TITLE
Memory leak with mina easing and animate

### ISSUE THREAD

**Issue by mike-tempest** [adobe-webplatform/Snap.svg#374]
When using lots of animations, memory leaks very quickly appear as it looks like the reference on the finish event of the animation to mina is never removed. That or the window event inside of mina is never being cleared.

Please use this demo to see this issue.
http://demos.michaeltempest.com/hill-valley.html

**Comment by DmitryBaranovskiy** [comment]
Duplicate of #369.

**Comment by mike-tempest** [comment]
Sorry, saw the other after posting this
