### ISSUE TITLE
Load Event type undefined

### ISSUE THREAD

**Issue by bakajin** [adobe-webplatform/Snap.svg#392]
Seems that the event.type string is undefined when using Snap.load.
The event also fires twice, I am guessing a start and complete. 

Is there any way to confirm this, would make my life easier handling if a file actually finished loading.

**Comment by ibrierley** [comment]
Example code is always useful!

**Comment by bakajin** [comment]
But of course, my bad.

for instance

function loadAssets(assetList, base) {
					for(a = 0; a < assetList.length; a++) {	
						Snap.load((path + assetList[a] + ".svg"), onSVGLoaded);

					}
		}

function onSVGLoaded(loaded) {
        // on each file load this is fired twice, I guess a load start and complete
	console.log(loaded.type); //produces undefined
}

**Comment by ibrierley** [comment]
But there isn't a loaded.type (loaded will be a fragment)...

Try console.log( loaded ) and then s.append( loaded );

**Comment by bakajin** [comment]
Sure, that I do and works no problem.
But I m trying to load various svg files into arrays and then build layouts out of those later.

So now it actually fires the onSVGLoaded twice (for one file), which then totally throws the array.push(loaded).

And if already tried logging the loaded (fragment) and weeded through the values but there is nothing I can see which shows if it is the load start or load complete or why it fires twice.

**Comment by ibrierley** [comment]
Any possibility you could get a testing example up on a jsbin or something ? It doesn't happen on mine, so it could be its a problem with a specific version or something.

**Comment by ThomasBrierley** [comment]
I've tested the Snap.load method in isolation on v0.4.1, v0.4.0 and v0.3.0, the callback is only called once in each.

Your sample code shows use of Snap.load inside a loop, it's possible the bug is here. You could try inspecting the loop to find out what is actually being passed to Snap.load in each iteration.

If you can't find an issue with your code then we need a working test case to debug, that's somewhere between a single Snap.load call and your use case.

**Comment by bakajin** [comment]
Indeed it was in this particular case. So i have sorted the problem in this particular case (and am feeling my way around Snap). My original question was concerning the event.type though, or rather the missing event.type in the load event. Which is something I used before (in flash for instance) to make my load event function more universal. So I think it would be helpful if it was there but for now I will live without. 

Thanks a bundle for all the help (to a n00b)

**Comment by ThomasBrierley** [comment]
You're welcome

According to the docs you can use [Snap.ajax](http://snapsvg.io/docs/#Snap.ajax) which is supposed to return the XMLHttpRequest object. I haven't used it myself but you may be able to get the type property from that.
