### ISSUE TITLE
Animation of rotation by more than 360 degrees

### ISSUE THREAD

**Issue by evtik** [adobe-webplatform/Snap.svg#395]
Got strange behavior when trying to animate rotation by more than 360 after applying some transform (scale or rotate). In this case there is no propeller-like animation, the element rotates by the angle which seems to be calculated as the remainder of dividing the given angle by 360. Moreover, it seems to be shrunk/spread during the animation. Snap version is 4.1

var paper = Snap(800,800);
var rect = paper.rect(10,10,48,48);
rect.transform("s.99"); // without this line it works as expected
rect.click(function(){
    this.stop().animate({transform: "t200,0r1200"}, 2000);
});

More interesting is that when using Snap 3.0 replacement of transform strings by matrix transforms gives the desired behavior.

var m = new Snap.Matrix();
m.scale(0.99);
rect.transform(m);

Am I missing something?

**Comment by ibrierley** [comment]
What feels a bit clunky from the above is animating values that aren't set, or don't get set during the animation. So in the first example, you have a 'scale' (which doesn't get animated), then animate translate and rotate (which aren't set). 

I feel like you will probably have more consistency by initialising all of the transforms and animating all of them (even if that value  stays the same).

**Comment by evtik** [comment]
Yep. I understood. Thanks. But one should preserve the order of transforms. "s.99t0,0r0" to "t200,0r1200s.99" won't work, though "t200,0r1200s.99" and "s.99t200,0r1200" are the same.

**Comment by ibrierley** [comment]
yes, order should be preserved, thats why its also useful to have an initialising transform.

They may look the same, but actually they aren't (not sure if thats what you mean).

"t200,0r1200s.99"  != "s.99t200,0r1200"  eg http://jsfiddle.net/1w3jssa1/

**Comment by evtik** [comment]
I meant the same (semantically) from the human point of view :-) Thanks again for the thorough explanation.
