### ISSUE TITLE
Please tell me where's the extending way like Raphael.fn/.st/.el

### ISSUE THREAD

**Issue by vrbvillor** [adobe-webplatform/Snap.svg#405]
In Raphael , there are `Raphael.fn`  `Raphael.st`  `Raphael.el`  and `Paper.ca` for custom functions.  But I can't find the similar method in Snap.svg.  Please tell me each of the above four.  Thanks.

```
Snap.plugin(function (Snap, Element, Paper, global, Fragment) {
    Snap.newmethod = function () {};
    Element.prototype.newmethod = function () {};
    Paper.prototype.newmethod = function () {};
});
```

In this passage, there aren't interfaces of Set(group) or customAttribute.  BTW,  what's the use of `global` and `Fragment`?

**Comment by ibrierley** [comment]
You can use the plugin method you list, each of the parameters references what it says, so Paper would reference the Paper being used here, Element would reference the element etc.

I don't think there's one for 'set', but you could write you own plugin for that.

global will be the global space I assume, and Fragment any fragment thats passed (fragments are used when loading in files or parsing markup in to Snap objects).

Example plugin creation...

Snap.plugin( function( Snap, Element, Paper, global ) {
        Element.prototype.getCenter = function() {
                var bbox = this.getBBox();
                return [bbox.cx, bbox.cy]
                };
});

**Comment by vrbvillor** [comment]
But there's no SET(Group) interface, how to write the plugin?  There's a Raphae.st for the SET object. And how to define a custom attribute?  Raphael has a "Paper.ca".

**Comment by ibrierley** [comment]
Ah I see, I thought you could just reference Paper.set.prototype in the plugin, but this doesn't seem to work as I thought.

It may be a workaround is needed, is there a specific problem you are trying to get around, or was it just this feature/bug that is enquired about ?

**Comment by ibrierley** [comment]
Ok, I think you can do it, I was using an old version...example...

```
var s = Snap("#svg");

Snap.plugin( function( Snap, Element, Paper, global ) {
     Snap.Set.prototype.moveAlong = function() {
         this.forEach( function( el ) {
             el.animate({ transform: 't50,0' }, 2000);
         });
     }
});

var c = s.circle(20,20,20);
var r = s.rect(60,60,60,60);

var set = new Snap.Set();
set.push( c,r );
set.moveAlong();
```

**Comment by vrbvillor** [comment]
Thanks for your help, I'll remember that.  ^3^
