### ISSUE TITLE
Update npm package to latest version

### ISSUE THREAD

**Issue by alexgoldstone** [adobe-webplatform/Snap.svg#406]
Current Snap.svg version is 0.4.1 but version in npm is 0.4.0

**Comment by stowball** [comment]
+1!

**Comment by steveostudios** [comment]
+1. I'm having a bug that was fixed in April 2015 (#364)

**Comment by robertbak** [comment]
+1

**Comment by trodi** [comment]
@DmitryBaranovskiy ?
:+1:

**Comment by tameraydin** [comment]
+1

**Comment by BrightShadow** [comment]
+1

**Comment by mradzinski** [comment]
+1

**Comment by thecotne** [comment]
@achicu 
@alharding 
@cantrell 
@edankwan 
@emalasky 
@jacobgoldstein 
@lmclister 
@mvujovic 
@oslego 
@piatra 
@silverma 
@vhardy

**Comment by gelevanog** [comment]
+1

**Comment by molisani** [comment]
+1
It just needs to be published.

**Comment by emmalewis** [comment]
+1

**Comment by johnny5th** [comment]
+1

**Comment by robertbak** [comment]
The npm version is updated to 0.5. This can now be closed.
