### ISSUE TITLE
Relative and absolute transfert

### ISSUE THREAD

**Issue by Psykobal** [adobe-webplatform/Snap.svg#411]
The function *transform('t100,0')* and *transform('T100,0')* are doing the same thing.
For example if I'm doing:
```javascript
       mysvg.transform('T100,10');
            /****some code****/
       mysvg.transform('t100,0');
```
I expect to find my svg in [200, 10] but instead it is in [100, 0], like it is always in absolute.

**Comment by ibrierley** [comment]
I don't think its designed to differentiate these days. It was in Raphael, but I think its different in Snap.

**Comment by Psykobal** [comment]
I found in the source code (function *transform2matrix*, line 1853) a boolean variable named *absolute* used to detect if it is 't' or 'T'. I don't understand the goal of this detection if it's not to make an absolute or relative transfert.
