### ISSUE TITLE
mina Object pause/resume not working as expected

### ISSUE THREAD

**Issue by elinfante** [adobe-webplatform/Snap.svg#412]
Hi guys, 

I am trying to pause some animations I apply to a dotted line. I can pause the animation but for some reason I cannot get to resume it afterwards. Is there a known issue? Has it been resolved?

Following the code to pause the line:

```
line.animate({x1:100, y1:200}, 5000,mina.linear );
line.inAnim()[0].mina.pause();
```
And this is to resume:
```
line.inAnim()[0].mina.resume();
```

thanks!

**Comment by ibrierley** [comment]
Just thinking back to an old bug and can't remember if it got fixed...

What happens if you run any other animation in the background whilst the pause is happening...ie choose any animation, run it for 1 min.
try the animation you want, pause and restart, see if its any different.

**Comment by elinfante** [comment]
I have several elements animating in the background, try to pause all of them and It works but then when I try to resume It just does not do anything.... very frustrating as I am following what the documentation says.

**Comment by ibrierley** [comment]
Could you put up a basic fiddle to play with

**Comment by elinfante** [comment]
Hi @ibrierley , 

I have set up a very simple test to show exactly what my problem is. Following SnapSVG documentation I am pausing the animation correctly but then It seems there is no way to resume it:

https://jsfiddle.net/jn7g48uw/

Any ideas?

**Comment by ibrierley** [comment]
Here's the hack I was meaning...look for the dummy element/animation.

https://jsfiddle.net/jn7g48uw/2/

var dummy = s.rect(-10,-10,0,0);
dummy.animate({ x: -10 },2000000);

Iirc there's a bug, where if you stop an animation and its the ONLY animation running, the timer/requestAnimation frame or whatever it is stops. So has a hack, you could have an animation running, or just run one when paused or something.

Its a bit of an ugly hack, but it may help understand where the problem is and figure a suitable workaround.

**Comment by elinfante** [comment]
thank you very much! It makes perfect sense. Just wondering If they will consider to fix this bug anytime soon.

**Comment by ibrierley** [comment]
In fact here's a slightly better work around. 

We don't need a dummy as we already have an element, and we don't need a long animation. All we need to do is perform any animation for 1ms for example. 

So simply adding this line when the resume is clicked should do it...

 dot.animate({ dummy: 0 } ,1); // animate any thing we don't care about for 1ms just to kick the timer off, once the main animation is resumed, we don't care.

https://jsfiddle.net/jn7g48uw/4/

**Comment by elinfante** [comment]
That was great, thank you very much for your help!
Hopefully they will fix it soon, meanwhile there is a workaround.
