### ISSUE TITLE
Unable to flip SVG

### ISSUE THREAD

**Issue by isteven** [adobe-webplatform/Snap.svg#419]
Hi all,

I'm totally new to SVG. I am trying load an existing SVG file, clone one of the <code>g</code> element in it, shift it's position, and flip it.

    var snapObj = Snap(".mascot");

    Snap.load("img/water.svg", function(f) {
        var waterRightHand = f.select('.water-right-hand-closed');
        var waterLeftHand = waterRightHand.clone();
        waterLeftHand.transform('t250,-50');    // OK to this point
        waterLeftHand.transform('s1,-1');         
        ....
        snapObj.append(f);
    }    

Everything is OK until the <code>transform</code> syntax. However, If I flip it with the last syntax (<code>waterLeftHand.transform('s1,-1');</code>), the waterLeftHand element doesn't appear on the screen. 

If I remove that scale syntax, the waterLeftHand element will appear again.

Any help would be appreciated. Thanks.

**Comment by ibrierley** [comment]
I think you may need to put an example on a jsfiddle. Its worth bearing in mind the scale will overwrite the  previous transform, so it maybe that ?

If you want to transform and scale, try 't250,-50s1,-1' for your single transform command.

**Comment by isteven** [comment]
@ibrierley , 

Thanks for the response. 

So am I correct to assume that, by default all transformations are always applied to the original attribute of an element (hence overwriting)? 

Actually.. the code is pretty much just like that. Gotta go now, I'll try to provide a fiddler later when I'm back.

**Comment by ibrierley** [comment]
Yes, I can't remember if you can still use '...' (three dots) to signify adding to a previous transform or not, but by default it will overwrite the transform.

**Comment by isteven** [comment]
@ibrierley ,

Ok, here's the fiddle. Let me know if you need me to paste the SVG as well.

http://jsfiddle.net/4nmj535o/

**Comment by ibrierley** [comment]
Working example would be good :). Did you test adding the transform string like suggested ?

**Comment by isteven** [comment]
I did try the transform string you suggested but it didn't work (or maybe I was doing it wrong).

Anyway, here's the updated fiddler: http://jsfiddle.net/4nmj535o/1/

Mind you, I'm no expert in creating SVG images either :p

FYI I use Snap SVG version 0.4.1

**Comment by isteven** [comment]
@ibrierley , 

Suddenly it works, no idea why..  Thanks for the help anyway, much appreciated.

Closing the issue.
