### ISSUE TITLE
Is this project still under development? if yes, will ther be a roadmap? 

### ISSUE THREAD

**Issue by RandallFlagg** [adobe-webplatform/Snap.svg#424]

**Comment by ibrierley** [comment]
It's a bit frustrating when there's no reply. It would be good to hear from Dmitry. Personally I think it would be good to apply a few of the essentials, like the memory leak fix done recently, and then maybe there could be further developments as plugins with a stable base.

**Comment by seudein** [comment]
Yes, looks abandoned. Nearly half the issues created are still open, last commit in April.

The docs leave much to be desired too (ie, clicking on `Element` doesn't scroll to `Element` section (+I'm not a fan of 1 page docs), no links to what `attrs` could be or what constitutes an `Element`, or why loading a `.svg` file and then trying to add it to the screen would result in `var g = f.select('g')` to return `undefined` when it worked in their sample code, which could be avoided if there's enough information on what a `Fragment` is).

I've been looking for a SVG library to use for easy tile display and not sure I'd want to use this one...

**Comment by DmitryBaranovskiy** [comment]
Sorry, but I am actively working on other project right now that consumes all my time. It doesn’t mean project is abandoned. Complaining is cheap.
