### ISSUE TITLE
snap.getBBox() returns 0 for all attributes

### ISSUE THREAD

**Issue by ajmas** [adobe-webplatform/Snap.svg#426]
When trying to get the bounding box for the snap element, all values are zero, even if the element.clientWidth returns a non-zero value.

This means I can't do:
```
  var snap = Snap('#mySVG');
  snap.getBBox().width;
```
since width returns zero. Instead we must do:

```
  var snap = Snap('#mySVG');
  snap.node.clientWidth
```

I would suggest that the snap bounding box takes it values from the clientWidth & clientHeight attributes.

See Fiddle https://jsfiddle.net/ajmas/k2h96c2w/

Tested in Chrome, Safari, Firefox & Opera

**Comment by DmitryBaranovskiy** [comment]
`getBBox` is not the same as clientWidth.
