### ISSUE TITLE
Snap.path.toCubic() produces NaN in output with degenerate arc input

### ISSUE THREAD

**Issue by rhashimoto** [adobe-webplatform/Snap.svg#430]
If the input path contains a degenerate arc, i.e. an arc that has a zero radius, `Snap.path.toCubic()` writes NaN into the output path. Degenerate arcs can be valid, just collapsed into one dimension, e.g.:

    <path d="m0,108 a 144,0 0 0 0 288,0">

The above path is just a horizontal line. Here is a [jsfiddle demo](https://jsfiddle.net/spvvu16x/) (run with the Javascript console open to see the resulting path string).

This error also occurs with `Snap.path.map()`, which I'm guessing exercises the same code.

I'm using Snap.svg 0.4.1. I see the issue on Chrome, Firefox, and Safari on OS X 10.10.5, and IE 11 on Windows 7.

**Comment by ThomasBrierley** [comment]
I had a quick look, this is simply due to a handful of potential divide by zeros (where the zeros are derived from the parameters), happy do a PR when snap becomes active again.
