### ISSUE TITLE
Example to use Snap.snapTo(values, value, [tolerence])

### ISSUE THREAD

**Issue by raavanan** [adobe-webplatform/Snap.svg#432]
I am trying to make an element(box) snap to a another element(line) while dragging close to it. I am using    
this https://github.com/oslego/Snap.FreeTransform tool to drag and freeTransform.

**Comment by ibrierley** [comment]
You could take a look at http://robsneuron.blogspot.co.uk/2013/11/using-snapsvg-to-create-box-that-snaps.html for an example.

**Comment by raavanan** [comment]
@ibrierley thanks.
