### ISSUE TITLE
How can I retrieve the Element in an event without 'this'?

### ISSUE THREAD

**Issue by CicholGricenchos** [adobe-webplatform/Snap.svg#436]
I am using ES6 Arrow Function, which will overwrite the 'this'.
Here is no way a node can reference the element?

**Comment by ibrierley** [comment]
Can you show an example where it will get overwritten

**Comment by CicholGricenchos** [comment]
just:
```javascript
elem.mouseover((e) => {
	
});
```
ES6 Arrow Function keep the outer context.

snap.svg.js:L7335
```javascript
return fn.call(element, e, x, y);
```
Here is using `call` to change the `this`, I cannot access it in => function.
Meanwhile, I cannot retrieve the Element from Event object, because it is just a normal DOM Event, not containing any info of the Snap Element.

**Comment by CicholGricenchos** [comment]
Two suggestion:

Add an attribute to nodes referencing the element when creating them.
Insert the element into the event object when calling back event function.

**Comment by ibrierley** [comment]
You can always just 'Snapify' it, eg...

var c = s.circle(100,100,100).click( (e) => { console.log( Snap(e.target) ) } );

I doubt its so efficient, but I'm not sure modifying the DOM with references is ideal either, especially as you could have several variables pointing to the same DOM object, feels clunky.

I'm not really sure what the point using it here is though, over just using a normal func.

**Comment by CicholGricenchos** [comment]
it is avoiding `var that = this;`

well it works, thanks
