### ISSUE TITLE
Can you separate getSubPath in a single package

### ISSUE THREAD

**Issue by jasonHzq** [adobe-webplatform/Snap.svg#441]
I used to animating SVG path using stroke-dasharray before, but this method cannot animate a dashed line. So I begin to use getSubPath function of Snap to animate dashed line. 

The getSubPath function of snap is really a powerful function, but It's too heavy to import snap.js to develop such a simple animation. So I wish you can separate getSubPath in a single package.

**Comment by ibrierley** [comment]
Can you clarify 'this method cannot animate a dashed array'. Do you have a fiddle of what you are trying to achieve with the full load of Snap (to see if its possible without it).

**Comment by jasonHzq** [comment]
I mean the method of using stroke-dasharray cannot animate a dashed array, so I want to use getSubPath of Snap.

**Comment by ibrierley** [comment]
stroke-dasharray is an attribute, you can animate any attribute. Its not clear why you need a subpath for this without an example.

**Comment by jasonHzq** [comment]
I'm sorry for my poor English, now I have solved this problem, thank you!
