### ISSUE TITLE
Remove attributes from elements

### ISSUE THREAD

**Issue by vlribeiro** [adobe-webplatform/Snap.svg#442]
Elements in snap.svg have the [attr method](http://snapsvg.io/docs/#Element.attr), to get or set attributes to them.

But they lack the removeAttr counterpart, to delete those same attributes.

I used jquery as a workaround for this, but it would be nice to have the method on snap objects as well.

**Comment by ibrierley** [comment]
Tried just setting it to null/'' or something ?

**Comment by vlribeiro** [comment]
Yeah, setting it to null just changes the attribute value to the string "null".

**Comment by ibrierley** [comment]
In that case, I assume you could just do   element.node.removeAttribute("class"); or have a plugin which calls that, or have a simple plugin...

`Snap.plugin( function( Snap, Element, Paper, global ) {
        Element.prototype.removeAttr = function( attr ) {
            return this.node.removeAttribute( attr )
        };
});`

**Comment by vlribeiro** [comment]
Nice! I wasn't aware of the node attribute. Will certainly do this. :+1: 

Anyway, I think this should be a nice addition to Snap object :smile:

**Comment by DmitryBaranovskiy** [comment]
Setting attribute to empty string will remove it.
