### ISSUE TITLE
Randomly failing clone

### ISSUE THREAD

**Issue by matelich** [adobe-webplatform/Snap.svg#445]
Not sure if its bad form to cross-post from SO, but here goes http://stackoverflow.com/questions/35715302/randomly-failing-clone-in-snap-svg

I'm having a problem where occasionally `clone()` is failing inside `Element.insertAfter` because `el.node.parentNode` is null.

Inside top level html

    Snap.load(path, function (data) {
        window.picto_svg = data.select('svg');
        ...
        jQuery('#content').load('interior.html');
    }

Inside interior.html
    
    $(document).ready(function () {
        var svg_copy = picto_svg.clone();
        ...
    }

Am I just getting lucky that it usually doesn't fail? 9 times out of 10, when it fails, an F5 will fix it. I don't want to display the svg before cloning. I end up cloning it and adjusting the clone several times, so just want to keep one pure one.

**Comment by ibrierley** [comment]
Have replied on SO. I suspect you aren't calling clone after the svg has loaded, so call from the load function, rather than the ready function.

**Comment by matelich** [comment]
Thanks for the input, Ian. I did have to append the SVG to an element before reliably clone'ing it.
