### ISSUE TITLE
why no upgrades on this?

### ISSUE THREAD

**Issue by hybrisCole** [adobe-webplatform/Snap.svg#456]
Hello,

I use snapsvg, I had to do a couple workarounds to make it work on a webpack project. It feels weird that this is not straightforward to get along with AMD.
Good library but a little bit outdated I guess? I would expect more releases since this is backed from Adobe, should I try another newer library instead?

Regards,

**Comment by jaapz** [comment]
@DmitryBaranovskiy could you please respond? Would be nice to get kind of a status update. Is this library still supported by you or should someone maybe take over maintenance?

**Comment by adam-beck** [comment]
@hybrisCole are there newer libraries for SVG that you have taken a look at? I haven't done much research but from the little I did do I didn't see anything that even comes close to Snap.

**Comment by hybrisCole** [comment]
@adam-beck the only ones I've seen that are like in a decent level, are http://svgjs.com/ and https://bonsaijs.org/, still using snap tho, just had to make some workarounds to make it play along with webpack, not sure about the other ones but are alive (constantly maintained)

**Comment by lukaswelinder** [comment]
@hybrisCole: Could you share your workarounds?

**Comment by Sidewinder1138** [comment]
@DmitryBaranovskiy You've built a wonderful library here, Snap is awesome and it has convinced me that SVG is the way to go. Please give us at least a quick status update. If you've moved on to other things that's fine, but it would be helpful to know that. Thx!

**Comment by adam-beck** [comment]
@Sidewinder1138 good luck https://github.com/DmitryBaranovskiy?tab=overview&period=monthly

**Comment by Sidewinder1138** [comment]
@adam-beck Wow. He's vanished. Maybe got some bad programmer burnout...

**Comment by ibrierley** [comment]
I think last we heard we was busy with work.

It does make me think maybe we should do a fork of it or something and keep
critical updates going, not sure if anyone would be interested ?

**Comment by chasbeen** [comment]
Ian or who ever,
What are the most critical updates? 
(Eg: Top 10 in order explained in easy to understand terms), that would be a useful list from someone who has the big picture.
Are there any absolute show stoppers?
Charles chasbeen irunmywebsite.com      From: Ian <notifications@github.com>
 To: adobe-webplatform/Snap.svg <Snap.svg@noreply.github.com> 
 Sent: Friday, June 10, 2016 8:04 AM
 Subject: Re: [adobe-webplatform/Snap.svg] why no upgrades on this? (#456)
   
 I think last we heard we was busy with work.

It does make me think maybe we should do a fork of it or something and keep
critical updates going, not sure if anyone would be interested ?

**Comment by tonkonogov** [comment]
https://github.com/adobe-webplatform/Snap.svg/issues/424#issuecomment-166529594
