### ISSUE TITLE
Unable to select lineargradient tag in Firefox

### ISSUE THREAD

**Issue by sorenbryder** [adobe-webplatform/Snap.svg#458]
It is not possible to select a lineargradient tag in Firefox.

svg.select('lineargradient')  = null
svg.select('lineargradient#id')  = null
svg.select('#id')  = linieargradient with specified id

The problem only seems to exist in Firefox. It is no problem to select the lineargradient tag in other browsers.

**Comment by ThomasBrierley** [comment]
1. ```Snap.select``` is a light wrapper around ```document.querySelector```.
So this is not a Snap issue, it is a difference in native browser query selector engine behaviour.

2. The name of the ```linearGradient``` element is in camel case in the spec.
So FireFox is compliant and other browsers probably have more relaxed case sensitivity.

Try changing your selector to camel camel case and see if that fixes your issue.

**Comment by sorenbryder** [comment]
Thank you for the explanation. I used "linearGradient" as the name and now it works perfectly.
