### ISSUE TITLE
Use dynamically created node for initiation

### ISSUE THREAD

**Issue by novajohn** [adobe-webplatform/Snap.svg#461]
If a try to use just created SVG element with snap:
```javascript
window.onload = function() {
    var svgElement = document.createElement('svg');
    document.body.appendChild(svgElement);
    var snap = Snap(svgElement);
};
```
I have these errors then:
![errors](https://cloud.githubusercontent.com/assets/8023373/15667054/f1d54040-2735-11e6-847e-03c0ccb4c4d0.PNG)

Please, let me know how to fix it.

Thank you.

**Comment by ibrierley** [comment]
Any reason you are creating an element that way, and not using Snap ? I think you would need createElementNS and include the SVG namespace... 
https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS

**Comment by novajohn** [comment]
@ibrierley,

> Any reason you are creating an element that way, and not using Snap ?

It's a standard way to create a new element in **JS**. Is there a way to do it with **SnapSVG**?

>  I think you would need createElementNS and include the SVG namespace... 

Right, the solution is to use `document.createElementNS`:

```javascript
window.onload = function() {
    var svgElement = document.createElementNS("http://www.w3.org/2000/svg","svg");
    document.body.appendChild(svgElement);
    var snap = Snap(svgElement);
};
```
Thank you.

**Comment by ibrierley** [comment]
Normally, you could just do...

var s = Snap(800,800);

But it depends what control you want over where it gets inserted etc, otherwise the new solution you have is ok.

**Comment by novajohn** [comment]
I have many snap objects on page and I wrap them with **DIV**s to make them scrollable.
