### ISSUE TITLE
Fix to #430 in dev branch broke matrixproto.scale()

### ISSUE THREAD

**Issue by i-a-n** [adobe-webplatform/Snap.svg#472]
Hey there, just a quick note that updates recently pushed to the `dev` branch to fix issue #430  (specifically line 3784 here: https://github.com/adobe-webplatform/Snap.svg/commit/b14d35dd346d0d398e4513a5534001506ef0aa9a) have broken the `matrixproto.scale` function for us. I don't understand what the fix accomplishes, or where the variable `sy` is supposed to be defined now, but I had to roll back our version to fix our app.

Sorry I don't have time to research exactly why this broke snap.svg for us, but I wanted to mention it in case others are noticing this problem and searching for a fix.

**Comment by DmitryBaranovskiy** [comment]
Fixed
