### ISSUE TITLE
firefox: node.clientWidth and node.clientHeight return 0

### ISSUE THREAD

**Issue by adarrra** [adobe-webplatform/Snap.svg#473]
Hi,

please check my [fiddle](https://jsfiddle.net/Kitana/0br8mLs6/1/) 
in Chrome (53) everything works ok,
but in Firefox (48) both values equal 0

**Comment by ibrierley** [comment]
Not quite sure if this has anything to do with Snap. If you add the class via just SVG commands and not using Snap, do you see a different result ?

**Comment by adarrra** [comment]
I see...  You are right. So I should post this bug to firefox bug-tracker maybe...
Sorry for bothering)

**Comment by longsonr** [comment]
You'll be wanting to post this to the Chrome bugtracker. If you post it as a Firefox bug I will close it as invalid per 

https://www.w3.org/TR/cssom-view-1/#dom-element-clientwidth

If the element has no associated CSS layout box or if the CSS layout box is inline, return zero.

Note that SVG elements have no  CSS layout boxes.

**Comment by hipkiss91** [comment]
@adarrra If you're using jquery why not use this: https://jsfiddle.net/0br8mLs6/5/
Which negates the cross-browser issues.

Tested with firefox 52.

**Comment by SumNeuron** [comment]
This problem still exists

**Comment by ibrierley** [comment]
Is there anything to suggest as previously stated, that it's not a Snap issue ?

**Comment by longsonr** [comment]
I've explained why Firefox is correct with reference to the appropriate specification above so why shouldn't this issue be closed as invalid?
