### ISSUE TITLE
Snapsvg.io dosen't open using Microsoft Edge, Does that mean the library isn't supported in Microsoft Edge?

### ISSUE THREAD

**Issue by akinmail** [adobe-webplatform/Snap.svg#474]

**Comment by akinmail** [comment]
Wrong call

**Comment by akinmail** [comment]
Microsoft edge behaves erratically with this library

**Comment by tonkonogov** [comment]
Could you clarify please, what do you mean by "behaves erratically"?  It would be nice to see a sample fiddle as well

**Comment by DmitryBaranovskiy** [comment]
Bugs with description similar to “Something is wrong with X” will be closed with “Something is fixed with X” comment. :)
