### ISSUE TITLE
Morphing path returns error "attribute d: Expected number"

### ISSUE THREAD

**Issue by robertschneiderman** [adobe-webplatform/Snap.svg#477]
I am trying to morph one path into another, but strangely getting a "<path> attribute d: Expected number, "MNaNNaNCNaNNaNNaN…" error. This worked in another project, but returned a non fatal error.

```js
let s = Snap('#ot-creation > svg');
let flash = Snap.select('#flash-start');
flash.animate({d: "M532.9,254.8l-142.1-66.4l85.7-108.6L532.9,254.8z"})
```

**Comment by tet-web-dev** [comment]
similar problem here. Have you found a solution?
`        var s = Snap("#svgElement");
        var snakeBody = s.path("M221.25,0C54.25,24.5,0,236,0,236h65.25c0,0-31.5-176.5,156-214");
        snakeBody.attr({ fill: "#FF993F" });
        setTimeout(function () {
            snakeBody.animate({ path: "M221.25,0C66.75,20,0,236,0,236h65.25c0,0,14.77-194.484,156-214" })
        }, 3000);`

**Comment by dalisoft** [comment]
Hi. Please you can provide example in live mode with Jsfiddle, codepen or other?

**Comment by ThomasBrierley** [comment]
You have not provided a ```duration``` to the ```animation()``` method, it is a required property if you expect it to do any interpolation for you, otherwise you might as well use ```attr()```.

http://snapsvg.io/docs/#Snap.animation

**Comment by DmitryBaranovskiy** [comment]
What @ThomasBrierley said.
