### ISSUE TITLE
Support/Contribution

### ISSUE THREAD

**Issue by hipkiss91** [adobe-webplatform/Snap.svg#482]
Is this still something that people are actively working on? I'm just wondering because no new releases in almost two years?

**Comment by ibrierley** [comment]
Actively being worked on, would be a loose definition here :). There is the odd fork like Thomas Brierleys I think that I would consider a bit more up to date. However, apart from some fixes there, I'm not really sure how much more to do there is anyway. It's generally seemed pretty stable and reasonably well used, and you will typically get some help here/Stackoverflow/google group (and quite a few people know it due to similarity to Raphael as well).

**Comment by hipkiss91** [comment]
Awesome :). Sounds good. I must say - from what I've seen thus far I am impressed. Can't wait to start seeing what I can really do with it!!! ;) I'll contribute where/however I can too. I'm new to SVG but learning quickly. :)

**Comment by hipkiss91** [comment]
@ibrierley Does snap.svg only support basic creations - I.e. circle/rectangle etc? Can it handle other SVG elements such as <g> or <mask>?   
Additionally, I am seeing an error from my code:  
`parentSVG.type is not a function(…)`    
```
var parentSVG = Snap(Width, Height);
parentSVG .type('svg');
element.append(parentSVG);	
```

**Comment by ibrierley** [comment]
Not sure what you are trying to do with 'type' ? It's already an svg element.

It handles g and masks as in 

var myGroup = s.g() will create an empty group, or s.g( myRect, myCircle ) to group elements at the same time

Mask you can create eg http://snapsvg.io/docs/#Paper.mask

I also have a site with some examples on thats been helpful for some, e.g here is a mask example

http://svg.dabbles.info/snaptut-masks-new (click the run button)

**Comment by hipkiss91** [comment]
Thanks for bearing with me. I think I understand now, and the examples are really helpful! 

With the type I thought I could specify the 'tagName', if you will, from the docs http://snapsvg.io/docs/#Element.type

**Comment by ibrierley** [comment]
Must admit, I've never spotted that, not sure if that's a typo, in a different version or something else!

**Comment by hipkiss91** [comment]
@ibrierley How do I append a created SVG element to the perviously created SVG element?
So:
```
var element = Snap(#element);
element.attr(attributesObject);
var rect1 = element.rect();
var rect2 = element.rect(); 
rect1.append(rect2);
```

**Comment by nilssolanki** [comment]
Seeing that there are 197 open issues, I would think that there is still some work left to do?
