### ISSUE TITLE
xmlns attribute written out twice in <g> element

### ISSUE THREAD

**Issue by mrenzi** [adobe-webplatform/Snap.svg#487]
When I save an SVG document ( `theSvg.outerSVG();` ), it writes the xmlns attribute twice in the `<g>` element.  See here:
```svg
<g xmlns="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg">
```
Seems it shouldn’t need to write it there at all but anyhow, when the file is imported to Adobe Illustrator it doesn’t validate.  If I remove one of the xmlns attributes it will validate.

**Comment by DmitryBaranovskiy** [comment]
Seems to be fixed.
