### ISSUE TITLE
Matrix rotation is wierd in Snap?

### ISSUE THREAD

**Issue by bingomanatee** [adobe-webplatform/Snap.svg#489]
Maybe this is a SVG thing but rotation with the matrix doesn't animate nicely:

https://plnkr.co/edit/Fu2Xn1TmyrM4jQpHkY63?p=preview

**Comment by ibrierley** [comment]
Don't animate matrices, it typically won't do what you think. Animate with transformation strings, or by manipulating the transform string directly each animation.

**Comment by DmitryBaranovskiy** [comment]
While @ibrierley is correct, it should be much better behaviour with this commit: 2e6a2afa0ffc02182ea87734bc0955a19d67f41a
