### ISSUE TITLE
z-index moving

### ISSUE THREAD

**Issue by acterhd** [adobe-webplatform/Snap.svg#491]
Hello. I get problem. When I development my chess and 2048 hybrid, I see that elements overlap another when animation. How to up z-index of elements in group? 
This is not visible if no animation, but may showed when will animation.

**Comment by DavidBruchmann** [comment]
You can try changing the z-index in the keyframes. Could be done statically in the CSS or by javascript too.
As this solution seems so obvious to me, perhaps you experienced some problems there?

**Comment by acterhd** [comment]
Not need move z-index with animation, it need before animation...

**Comment by ibrierley** [comment]
Z-index as such is done by the order in the DOM. You can reposition the element by removing/readding the element, or adding the elements to the group or adding the group or whatever, so they are in the order you wish.

**Comment by DmitryBaranovskiy** [comment]
Not an issue.
