### ISSUE TITLE
Cannot read property 'mina' of undefined

### ISSUE THREAD

**Issue by iliyaZelenko** [adobe-webplatform/Snap.svg#496]
```
    Snap.plugin( function( Snap, Element, Paper, global ) {
        Element.prototype.pause = function() {
            this.inAnim()[0].mina.pause(); <<<
        }
        Element.prototype.resume = function() {
            this.animate({ dummy: 0 } ,1);
            this.inAnim()[0].mina.resume();
        }
    });
```

> Uncaught TypeError: Cannot read property 'mina' of undefined

```
        snap.selectAll('.target').forEach(function (elem) {
            elem.pause(); <<<
        });
```
This occurs after i call window.alert

**Comment by ibrierley** [comment]
Could you create a jsfiddle of what you are trying to do with just the basics for the error ?

**Comment by ThomasBrierley** [comment]
From: http://snapsvg.io/docs/#Element.inAnim
> Returns a set of animations that may be able to manipulate the current element

So ```inAnim()``` returns an ```{array}```, let add a loop:

``` JavaScript
Snap.plugin((Snap, Element) => {

	Element.prototype.pause = function () {
		let anims = this.inAnim();
		for (let i = 0; i < anims.length; i ++) {
			anims[i].mina.pause();
		}
	};

	Element.prototype.resume = function () {
		let anims = this.inAnim();
		for (let i = 0; i < anims.length; i ++) {
			anims[i].mina.resume();
		}
	};

});
```

This throws no errors, but still does not seem to function properly:

- Pause works on 0, 1...n elements when called at any time
- Resume works on 0, 1...n elements when called immediately after a pause
- Resume has no effect if deferred

I'm not very familiar with ```mina```'s methods so I might be doing something wrong, or it might be a bug in the resume method.

**Comment by ibrierley** [comment]
I think there's 2 possible problems. If you get the undefined message, it's possible you are using an old version of Snap, you can get the latest (as of writing) from https://github.com/adobe-webplatform/Snap.svg/archive/v0.4.1.zip or cdn at https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.4.1/snap.svg-min.js

If you find that it's just that the resume isn't working, it may be related to this problem a while back with single animations needing the animation loop to be running still. You can fake that, just by doing any animation...

Eg this.animate({ dummy: 0 } ,1); 

Example with hack in there... http://jsfiddle.net/kagyv12o/4/

`Snap.plugin((Snap, Element) => {

	Element.prototype.pause = function () {
		let anims = this.inAnim();
		for (let i = 0; i < anims.length; i ++) {
    console.log( anims[i] )
			anims[i].mina.pause();
		}
	};

	Element.prototype.resume = function () {
		let anims = this.inAnim();
		for (let i = 0; i < anims.length; i ++) {
      this.animate({ dummy: 0 } ,1); 
			anims[i].mina.resume();
		}
	};

});

var r = s.rect(10,10,100,100);
r.animate({ transform: 't300,0' }, 10000)

setTimeout( function() { 
    r.pause();
    setTimeout( function() { r.resume() }, 1000 );

}, 1000 )
`

**Comment by ThomasBrierley** [comment]
Thanks @ibrierley, the workaround pointed me in the right direction.

Mina sets up an animation loop internally for each element when you call ```animate()```. When the number of active animations reach zero the loop exits but the resume method doesn't restart it.

**Comment by ThomasBrierley** [comment]
...GitHub subverting my rewriting of history to cover my mistake :smirk:
