### ISSUE TITLE
Issue Management Delegation?

### ISSUE THREAD

**Issue by ThomasBrierley** [adobe-webplatform/Snap.svg#500]
I've read through most open issues (not at once). I know they are mostly "**questions**", a few "**bugs**" and the odd "**feature**" request... yet I am still lost. It would be nice to regain some kind of an overview of remaining bugs and interesting potential features.

I'm wondering if there is a way to delegate issue management for Snap so contributors can help? So we can label and close many of the resolved issues that are left open by their authors.

EDIT

I guess I answered my own question:

https://help.github.com/articles/creating-an-issues-only-repository/
https://help.github.com/articles/repository-permission-levels-for-an-organization/

Can't be done without also giving users repo write access... :confused: Shame, I thought this would be a common feature.

**Comment by ThomasBrierley** [comment]
An appropriate 500th issue milestone :smile:

**Comment by DavidBruchmann** [comment]
With all respect to your proposition, but also to your own words above:
how about closing this issue by yourself :-D

**Comment by ThomasBrierley** [comment]
I was hoping someone might have other suggestions...

**Comment by DavidBruchmann** [comment]
hehe, possible.
In general the idea is not so bad but even snap.svg might still have bugs many bugs are resided in the browsers or other software to display the SVGs, especially if animation is involved.
Don't know if you post bugs to browser-repos / bug-trackers too.
One example you find here: https://bugs.webkit.org/show_bug.cgi?id=166962
Another example: make a square in the middle of an svg and assign a stroke with short dashes and a large width (not thicker than the half width of the square), now look how different browsers render the corners.
Compatibility for SVGs is still a nice idea so far ...
Now I've polluted your proposition-thread, sorry.

**Comment by ThomasBrierley** [comment]
I am aware of the separation of responsibility, I've posted far to many detailed bug reports with test cases outlining fundamental SVG rendering bugs to the Chromium project, FireFox, IE11 and Edge (of course the later two are usually completely ignored). 

There are a few cross browser issues raised here and misconceptions about Snap vs Browser, I'm not suggesting highlighting those further... only clearing up issues in general so contributors have some clarity for bug and feature issues directly relevant to Snap.

**Comment by DavidBruchmann** [comment]
Yeah like that I understood you too, so perhaps you've luck getting an answer from Dmitry Baranovskiy - suppose he's the only one who could change there something.

**Comment by ThomasBrierley** [comment]
I'm gona close this because after much searching I can't see a way for this to work without giving full repo write access, there might be a way through GitHub's API but it wont be straightforward.

The best we could do is pseudo tag issues with a comment to give hints to Dmitri but that doesn't really help as much... e.g "This can be closed" or "Label: Bug", "Label: Question"

**Comment by ThomasBrierley** [comment]
I just thought of a way to help close issues, It's simple but a hack. GitHub automatically closes issues referenced in a PR when prefixed with the appropriate keyword e.g "**Close**".

I could for instance open an empty PR "**Issue Purge**", then go through and add each issue in to the PR body with a short reason for each. This way Dmitri still gets to pull the trigger but only has to hit a single button.

@DmitryBaranovskiy are you up for this?

**Comment by ThomasBrierley** [comment]
I'll try this at some point, as a list of stuff to close at least.
