### ISSUE TITLE
Please publish 0.4.1 on npm

### ISSUE THREAD

**Issue by jaapz** [adobe-webplatform/Snap.svg#502]
I'm not entirely sure why #485 was closed by the author, because 0.4.1 is not yet on npm.
Could it be published?

**Comment by ThomasBrierley** [comment]
Dmitry is just getting ready to cut the v0.5.0 release.

**Comment by DmitryBaranovskiy** [comment]
Just published 0.5.0

**Comment by studio-marweb** [comment]
Can you additionally publish 0.4.1? We are migrating from bower to npm and our system works stable with 0.4.1

**Comment by hipkiss91** [comment]
@studio-marweb You could pull v0.4.1 from github and build it locally?
