### ISSUE TITLE
Issue snap 0.5.1 getBBox or animate ?

### ISSUE THREAD

**Issue by pfx81** [adobe-webplatform/Snap.svg#505]
With this code the red square is supposed to turn from its center but this is not the case with snap 0.5.1?
Can anyone confirm if this is a bug?

```js
var s = Snap("#svg1"); 

var r1 = s.rect(100,100,100,100).attr({fill: 'green'});
var r2 = s.rect(100,100,100,100).attr({fill: 'red'});
var r2BB = r2.getBBox();

r2.animate({transform: "r" + [90, r2BB.cx, r2BB.cy]}, 5000);
```
tanks

**Comment by pfx81** [comment]
Sorry for not deepening. The problem seems to be related to el.animate. The square does not rotate from its center with this code : `r2.animate({transform: "r90,150,150"}, 5000);`

**Comment by ibrierley** [comment]
Can confirm this. Wonder if this is related to the recent matrix animation changes I think I read about.

**Comment by ThomasBrierley** [comment]
Just chiming in here... this is broadly affecting most of my existing animations too.

**Comment by ibrierley** [comment]
I think there's a problem with rotations of 360 degrees not working (or 350 rotating backwards iyswim)

**Comment by ThomasBrierley** [comment]
```git bisect``` points to 2e6a2af (un-buildable) and 1492b44 (first broken)

**Comment by DmitryBaranovskiy** [comment]
This commit should fix this issue. Equalising transforms is a complicated task.
