### ISSUE TITLE
Snap.atan2 passes only one number to Math.atan2

### ISSUE THREAD

**Issue by mscuthbert** [adobe-webplatform/Snap.svg#507]
I'm a complete Snap newbie, so feel free to bite.  :-)   I think there may be an issue with Snap.atan2 which passes only one value to math.atan2(), when, to my knowledge, it should be taking (y, x) and passing both to math.atan2()

https://github.com/adobe-webplatform/Snap.svg/blob/master/src/svg.js

(Thanks for Snap -- lots of fun!)

**Comment by ThomasBrierley** [comment]
Yup, I guess no one actually used it before :stuck_out_tongue:
