### ISSUE TITLE
Snap future.

### ISSUE THREAD

**Issue by hipkiss91** [adobe-webplatform/Snap.svg#508]
Is there a plan to rewrite in ES6 or similar?
I'd love to get my teeth sunk into this lib as I use it and am interested in what can be achieved with it. Especially considering people are using SVG's more and more these days.

**Comment by DavidBruchmann** [comment]
What is similar to ES6?

**Comment by ThomasBrierley** [comment]
I guess one the JavaScript-ey super-set languages designed for transpiling into JavaScript like TypeScript or CoffeeScript. They are often considered among the options when looking at re-writing in the latest ES, although I think ES6 makes the current options redundant for the most part.

I do love a lot of the new features in ES6, but Snap has quite a large source and i'm not sure how it would immediately benefit from such a large effort. If you are after performance improvements there are way lower hanging fruit than the latest ES6 sugar.

Do you have a specific needs like ES6 imports or something?

**Comment by hipkiss91** [comment]
@ThomasBrierley I don't have any requirements particularly. My main thinking was it could make it easier to manage and install. I'd like to try and contribute if I can :)

**Comment by DavidBruchmann** [comment]
I think for updating / upgrading or specializing should be a reason, especially if usage gets more complicated or somehow limited. Currently the library is easy to use even for beginners. Having a stack like with node.js or composer and CoffeeScript or TypeScript is at least for beginners harder.
And don't get me wrong @hipkiss91, you might have some skills I don't know about, concerning snapsvg.js you seem being a beginner, it's no fault or any point for critics, but to change or improve something you don't know very well might be quite difficult.

**Comment by hipkiss91** [comment]
That's a fair assessment. Regardless though, I would still like to try and contribute if I can - the best way to learn is to do. :)
I love the lib and I can see it being used more and more by industry as more and more devs realise the benefit and potential of SVG's.

**Comment by ThomasBrierley** [comment]
> That's a fair assessment. Regardless though, I would still like to try and contribute if I can - the best way to learn is to do. :)

Exactly :smile: have a look in the source, see if you can figure out how to add or change what you want. You will at least learn something or get better at reading code (A somewhat separate and variably difficult skill from simply writing your own).

If you succeed you can always try a PR and others can at least review it and feedback if not merge.

**Comment by DavidBruchmann** [comment]
@hipkiss91: I won't stop you making useful things ;-)
Just a question for yourself: is it useful directly lifting the library from the existing technical state to another or is it perhaps better to stick to the functionality, fixing some bugs, spending some demonstrations, improving the documentation, ...
