### ISSUE TITLE
attr() styling issue

### ISSUE THREAD

**Issue by hipkiss91** [adobe-webplatform/Snap.svg#510]
I have the following code:
```
const svgNameSpace = 'http://www.w3.org/2000/svg';
let attrs = {fill: '#428ccc', stroke: "#000", strokeWidth: 5};
let element = document.createElementNS(svgNameSpace, 'svg');
document.body.appendChild(element);
this._containerSVG = Snap(element);
let newSVG = this._containerSVG.rect();
this._buildSVGAttributes();
function _buildSVGAttributes(attributes, parentSVG){
	parentSVG.attr(attributes);
}
```
I'm trying to figure out why this isn't working. The SVG builds and attaches to the DOM and the attributes also attach to the svg element but they don't actually apply, so i don't actually see any styling. Am I initiating `Snap()` incorrectly? Should it only be a reference to an element instead of the actual element?

**Comment by DavidBruchmann** [comment]
It's quite uncommon what you're doing.
You're instantiating the svg by yourself instead by usage of of snap.
But then you want to build a single element with snap.
Don't want to say it's impossible but probably the hard way.
Concerning display of your dom: you don't gave any measures, so it's invisible.

**Comment by ibrierley** [comment]
Put a testing example on a jsfiddle.

**Comment by hipkiss91** [comment]
@DavidBruchmann Please can you elaborate? I thought you couldn't created an `<svg>` using Snap, I thought you had to already have an `<svg>` element already in the DOM?

**Comment by DavidBruchmann** [comment]
You can attach Snap to an exesting SVG by Snap('#mySvg') or you can create a new one with Snap(122,211).
There are still more options, you can read about it in the API:
http://snapsvg.io/docs/#Snap

**Comment by DavidBruchmann** [comment]
The attributes probably never apply because you never pass the to your own function.
You have to write:
this._buildSVGAttributes(attrs, this._containerSVG);
to call your function.
So in general your first lines are not wrong but not needed.
Nevertheless, measures (width and height) are required to show anything.

**Comment by hipkiss91** [comment]
Ok, thank you. This has indeed solved my conundrum. Creating the initial `<svg>` with Snap instead of creating it separately is what threw me. SVG's are displaying correctly within the DOM. :)
The not passing parameters through in my function was just a typo for this post, and is indeed correct in my code. Thanks for the help.
