### ISSUE TITLE
Multiple steps/frames in animation

### ISSUE THREAD

**Issue by burouc** [adobe-webplatform/Snap.svg#511]
I am trying to animate a path, to achieve the desired effect I broke the animation in a few steps and I am triggering the next step in a callback like this:
`path.animate({path: newPath}, 1000, function () {
    animatePath(path, nextPath);
});`

This does animate all the steps, but there is some lag between the steps, is there a better way to achieve this? It would be nice if you could pass an array of animations to the animate function, just a thought,

**Comment by ibrierley** [comment]
You could do something similar to http://svg.dabbles.info/snaptut-animateframe

Something I've been thinking similar could be added to the main code, as it is something that seems to be called for a bit.

There shouldn't be any noticable lag other than the set delay, so if you get some extra lag somewhere, it may be worth producing a minimal test case highlighting the problem.
