### ISSUE TITLE
Rotation transform not working anymore

### ISSUE THREAD

**Issue by daign** [adobe-webplatform/Snap.svg#517]
Consider this [codepen](http://codepen.io/anon/pen/vOwRga).

If you change the Snap version to the most current release 0.5.1 the rotation in the first circle is not working anymore. I guess it's interpolating the matrix instead of rotating properly.

This made me go back to an older version of Snap for my project.

(Ignore the second circle. I didn't make the codepen. It's from an old [stackoverflow ](http://stackoverflow.com/questions/32069603/rotating-object-with-matrix-rotate-in-snap-svg-morphs-the-object/32070570?noredirect=1)question.)

**Comment by ibrierley** [comment]
Possibly related to https://github.com/adobe-webplatform/Snap.svg/issues/505 ?

**Comment by ibrierley** [comment]
Closing as assuming covered by 505
