### ISSUE TITLE
Snap filter feGaussianBlur?

### ISSUE THREAD

**Issue by hipkiss91** [adobe-webplatform/Snap.svg#523]
Can Snap do blurs with a `stDeviation` instead of just with `x, y`?

If not is there a conversion or a slightly different method that snap uses?

http://snapsvg.io/docs/#Snap.filter.blur

**Comment by ibrierley** [comment]
x,y is the stdDeviation in this case to my understanding (not quite sure if that answers your question).

**Comment by hipkiss91** [comment]
Ok, my question then is how do they correlate to one another? Because std is a single number and x,y are two.
(Might be a dumb question, sorry if I'm missing something obvious.)

**Comment by ibrierley** [comment]
stdDeviation can be a single number or two numbers.

If it's 2 numbers, the blur will vary in how much it blurs horizontally or vertically. Eg stdDeviation of 0,10 would pretty much only blur in the vertical iyswim.

**Comment by hipkiss91** [comment]
@ibrierley Ok, that makes sense. But does Snap default to applying the stDeviation, if it's a single number, in the x direction or does it apply the std to both x and y?

**Comment by ibrierley** [comment]
So here's the code...

```    Snap.filter.blur = function (x, y) {
        if (x == null) {
            x = 2;
        }
        var def = y == null ? x : [x, y];
        return Snap.format('\<feGaussianBlur stdDeviation="{def}"/>', {
            def: def
        });
    };
```

So looks like if there is no x, a default of 2 is applied. If there is no y then a single x is applied. But if a single x has applied, then that is actually applied to both (that bits not in the code, just in how stddeviation works)

So blur() would effectively be 2,2
blur(0,3) would effectively be 0,3
blur(3) would effectively be 3,3
blur(3,0) would effectively be 3,0

I think (not tested)

**Comment by ibrierley** [comment]
Closing as no further issue raised
