### ISSUE TITLE
Why does `fill: currentColor` default to black?

### ISSUE THREAD

**Issue by hipkiss91** [adobe-webplatform/Snap.svg#526]
Why does `fill: currentColor` default to `fill: #000000` ?

**Comment by ThomasBrierley** [comment]
Black is the default fill colour for SVG shapes, not Snap's default but SVG's... just like HTML has a bunch of defaults through user agent stylesheet.

**Comment by hipkiss91** [comment]
I'm trying to replicate an SVG from a website and on the website it's currentColour, which is actually blue?

**Comment by ibrierley** [comment]
Maybe it would be good to replicate the issue on a jsfiddle with a minimal example.

**Comment by hipkiss91** [comment]
I can't replicate the issue in jsfiddle.

**Comment by hipkiss91** [comment]
@ibrierley  Replicated it:
https://jsfiddle.net/90kc8kj1/1/

**Comment by ibrierley** [comment]
I think currentColor is only a style option, not an svg attribute (but as ever I may be wrong). So maybe this ?
https://jsfiddle.net/90kc8kj1/2/

**Comment by hipkiss91** [comment]
Interesting. I'll give it a go, but in the original the fill property isn't applied within "style"?

**Comment by hipkiss91** [comment]
That's fixed it! :D. Thank you.

**Comment by hipkiss91** [comment]
@ibrierley Actually, if you look at http://snapsvg.io/start/ at stage 3 it shows fill being within the .attr method. Thoughts?

**Comment by ibrierley** [comment]
I think there's possibly a bit of confusion...SVG can have both attributes or styles for quite a few settings (and both can be present), and the same name can be used for either in many cases.
fill for example is one of these, so you can set fill as an svg attribute or a style.
Style will take precedence over an attribute following normal css cascading precedence (I think!).

So if you have style="fill: yellow" AND fill="green" on the element, it will appear as yellow. If you remove the style, it will appear as green.

Now to add to the confusion just mentioning it in case you dig deeper, I think there's at least one thing where if you set an attribute in Snap, it set it as a style underneath in the actual SVG. Fill may be one of them. I've always thought this incorrect (if I set an attribute, I want that attribute set, not a style!), but it's been open to debate. I can't remember if that was fixed, or if preferred that way.

**Comment by hipkiss91** [comment]
@ibrierley I appreciate all your help with understanding Snap and more about SVG's :).
Could I pick your brain on a slightly different thought as well?
So I'm also trying to re-create a linearGradient with Snap and I'm finding it difficult when 1 linGrad doesn't have any `<stop>` children (or stop-colour attr/style) and instead references to another linGrad that has the colours. However, the linGrad with colours doesn't have any coords and therefore doesn't get built by Snap. Below is an example of the svg's I'm replicating. Thoughts?

```
<svg>
	<defs>
		<linearGradient id="linearGradient4505">
			<stop offset="0" id="stop4507" 
				style="stop-color:#dcbf19;stop-opacity:1">
			</stop>
			<stop offset="1" id="stop4509" 
				style="stop-color:#dcbf19;stop-opacity:0">
			</stop>
		</linearGradient>
		<linearGradient xmlns:xlink="http://www.w3.org/1999/xlink" 
			xlink:href="#linearGradient4505" id="linearGradient4761" 
			gradientUnits="userSpaceOnUse" x1="14.58" y1="14.06" x2="106.25" y2="94.79">
		</linearGradient>
	</defs>
</svg>
```

**Comment by ibrierley** [comment]
If there is anything specific that Snap can't do, which I would understand with more complicated filters, you can always Snap.parse() the raw svg, couple of example at http://svg.dabbles.info/snaptut-fobject and http://svg.dabbles.info/snaptut-parse

Append the fragment that is returned from a parse().

If those elements in the raw svg have id's you can still reference them and animate them or whatever, but some things you may need to delve into changing with pure j.s if it's something Snap doesn't understand.
