### ISSUE TITLE
store Empty string in Snap.set

### ISSUE THREAD

**Issue by pfx81** [adobe-webplatform/Snap.svg#529]
With Snap.svg 0.4.1
If you put an empty string in a Snap.set when it is removed it is undefined.
Is it by design or a bug?
I try this:
`       var s = Snap.set();
        s.push("");
        s.push("t");
        console.log(s.pop()); 
        console.log(s.pop());
`
Thank you

**Comment by ibrierley** [comment]
Well that's what the code says, so in a way it's by design.

Maybe it doesn't have to be that way, but I wonder why would you want to push "" or "t" on there out of interest (just use a regular array or something if you want type of stuff)?

**Comment by pfx81** [comment]
I use a Snap.set to keep the sequence of states of an element via el.transfrom().local . But when the element has not undergone any transformation element.transform().local return an empty string that is kept as "undefined" in a Snap.set.
Thank you

**Comment by ibrierley** [comment]
Why not just use an array ? Not really understanding what Snap.set is bringing here over an array if it's not containing SVG elements.

**Comment by pfx81** [comment]
You are right. I did not understand the restriction of Snap.set to SVG elements. I will use array to manage the stack of states.
Thank
