### ISSUE TITLE
Does Snap work with templates ?

### ISSUE THREAD

**Issue by ivar** [adobe-webplatform/Snap.svg#53]
Just a general question - how would Snap work with a js templating tool. (eg: moustache or handlebars) ?

**Comment by yeyaolong** [comment]
> +1
> 
> index.html file as below: This HTML is compiled with Handlebars
> `<div id="svg"></div>`
> 
> index.js file as below:
> 
> ```
> var s = Snap("#svg");
> var bigCircle = s.circle(150, 150, 100);
> ```
> 
> When i executed my code. It is showing me following error:
> `TypeError: s.circle is not a function`

maybe you can change your code like this:
index.js
`<svg id="svg"></svg>`
