### ISSUE TITLE
Where will i can find properties a attribute transform ?

### ISSUE THREAD

**Issue by semiromid** [adobe-webplatform/Snap.svg#534]
Where will i can find properties a attribute transform ?

                Element.attr({
                        transform: 'What should be here?"
                });

**Comment by ibrierley** [comment]
A transform string would go in there. This can either be an SVG transform string (eg 'translate(10,10) rotate(90,20,20)' type thing, or a Snap transform string, which can be 't20,20r90,s2' would mean translate 20,20, rotate 90 (around center) and scale 2.
