### ISSUE TITLE
There is Problem with "Rotate" in example on http://snapsvg.io/demos/

### ISSUE THREAD

**Issue by semiromid** [adobe-webplatform/Snap.svg#535]
There is Problem with "Rotate  animation the arrow" in example on http://snapsvg.io/demos/
https://www.youtube.com/watch?v=yxP0KDIJO6g&feature=youtu.be

I have the same in my code.
https://www.youtube.com/watch?v=U8AkkixeI8M&feature=youtu.be

I use Google Chrome 57.0.2987.133

How i can solve the problem?

**Comment by semiromid** [comment]
I understoond
If use (No problem) - <script src="http://svg.dabbles.info/snap.svg.js"></script> 
If use (Snap.svg-0.5.1 - snap.svg-min.js) - Will be problem

**Comment by DmitryBaranovskiy** [comment]
Fixed on `dev` branch.
