### ISSUE TITLE
circle: x\y or cx\cy?

### ISSUE THREAD

**Issue by BasiiSania** [adobe-webplatform/Snap.svg#537]
NOT works:
`  cl = s.circle(1, 1, 9);  cl.animate({x: e.pageX, y: e.pageY}, 1000, mina.linear);`
Works:
`  cl = s.circle(1, 1, 9);  cl.animate({cx: e.pageX, cy: e.pageY}, 1000, mina.linear);`

**Comment by ibrierley** [comment]
Yes, this is correct. Circle uses cx, cy as per the SVG spec and not x,y.

**Comment by BasiiSania** [comment]
Then, as I see, the little misspelling in docs:

> Paper.circle(x, y, r)
Draws a circle
Parameters
x    number    x coordinate of the centre
y    number    y coordinate of the centre
r    number     radius
