### ISSUE TITLE
get path of rect

### ISSUE THREAD

**Issue by ollakalla** [adobe-webplatform/Snap.svg#538]
I have svg image, and the image border is rectangle, 
I want to get the path of rectangle so i can use Snap.path.isPointInside function
to know what circles inside the border of rectangle and what is out

**Comment by ibrierley** [comment]
Just thinking out loud, I suspect if you are just testing against a rect, a simple box test may be faster than converting to a path... eg https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection and put it in a plugin maybe ?

**Comment by ollakalla** [comment]
I already made code for path, but it works with shape that have path


    var outlinePath= "M 49.005478,95.20593 48.324847,82.27393 25.183371,83.29488 19.398002,30.545926 41.51853,28.504031 40.157267,12.168871 89.162745,8.765713 187.85433,38.373189 193.98002,37.692558 673.82533,181.98647 1124.949,242.727 l -0.062,29.12435 -6.641,-0.0785 0.015,5.68947 29.1448,-0.21761 0.1114,15.73349 3.6287,-0.035 0,-22.53585 14.5393,0.72696 0,-12.35837 62.1553,0.36348 0,8.72356 1130.9473,-0.92305 0.1441,338.23869 c 0.013,29.63348 0.035,59.26697 0.099,88.90039 l -1131.9168,1.23829 0,11.63141 -33.2586,0 0,-9.63226 -43.9465,-0.12457";
    result.forEach(function(ap){
        // basic path
        if( Snap.path.isPointInside(outlinePath, ap.x, ap.y) ) 
        {
            insideStation = insideStation + 1;
            circle = s.circle(ap.x, ap.y, 5).attr({ fill: "#00ffcb",id : ap.id});
        }
        else
        {
            circle = s.circle(ap.x, ap.y, 5).attr({ fill: "#ff0000",id : ap.id});
        }
    });
`
but i want to get the path for rectangle to make this code working

**Comment by ibrierley** [comment]
How about something like...

`
var rectPath = function(x,y,width,height) {
  s.path(["M",x,",",y,'L',(x+width),",",y,"L",(x+width),",",(y+height),"L",x,",",(y+height),"Z"].join(''));
}

**Comment by ollakalla** [comment]
That is working with me thanks
