### ISSUE TITLE
Seeing strange rotation behavior between 0.4.1 and 0.5.1

### ISSUE THREAD

**Issue by voodoochild** [adobe-webplatform/Snap.svg#550]
I've been working on building out a radial dial UI component and had it working fine (https://codepen.io/blacklionchest/pen/gRoKao) with snapsvg 0.4.1. I copied the code locally this morning and ran it with snapsvg 0.5.1 from npm and now see strange behavior when rotating slots on the lower right side of the dial (https://codepen.io/blacklionchest/pen/MoqWXL). It looks like perhaps the origin of the rotation transformation isn't being maintained correctly? Left and right arrows move the dial in both demos.

**Comment by ibrierley** [comment]
I think there's a bug in 0.5.1 which has been fixed (you could try the dev branch I think), still waiting in 0.5.2
