### ISSUE TITLE
Snap doesn't retrieve an SVG element by a numeric ID

### ISSUE THREAD

**Issue by twasyl** [adobe-webplatform/Snap.svg#552]
Given the following code where the SVG element has a numeric only ID:
```html
<svg id="123" width="500" height="500" />
<script>
   var s = Snap("#123");
   s.circle(50, 50, 50);
</script>
```
When the page is loaded
Then `s == null`

However, if the SVG element has the ID `abc`, `s != null`.
Moreover, if the SVG element has the ID `abc123`, `s != null`.
Finally, if the SVG element has the ID `123`, then `Snap(document.getElementById('123'))` doesn't return `null`.

This was tested in version 0.5.1

**Comment by ibrierley** [comment]
Numeric id's aren't supported as css selectors (it's the 1st digit being a number which is the issue), it's not a Snap thing, it's the original spec (I think). I think html5 spec may support it, but css spec doesn't.

https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier

You may be able to use something like [id='1800'] as a selector (untried), but ultimately as it's unsupported, I would make sure any id doesn't start with a number.

**Comment by twasyl** [comment]
OK, thank you for your quick response. I wasn't aware about this particularly point in the spec.
Thank you.
