### ISSUE TITLE
My code not work on Safari

### ISSUE THREAD

**Issue by blacksaheb** [adobe-webplatform/Snap.svg#554]
I am using Snap for animation, I have pizza slice when  click on it, it goes backward, it work fine in Chrome and Mozilla but it not work on Safari don't know what is the issue.
one can see example on below link https://www.swiftpizza.com/pizza/

**Comment by ibrierley** [comment]
Don't transform an svg element, put in a group and transform that.

**Comment by blacksaheb** [comment]
Thanks it work :)
