### ISSUE TITLE
Repeating animation

### ISSUE THREAD

**Issue by glynthink** [adobe-webplatform/Snap.svg#556]
I am trying to repeat an animation via the callback function.  But the callback seems to be fired immediately, not when animation is finished.

here is an example i made, where i want the wave to keep moving left

https://codepen.io/thinkdesign/pen/JybJOq

**Comment by ibrierley** [comment]
With a callback, you need to pass it a function to call, not the result of a function (unless that's returning another function).

So give it 'animation' as a parameter and not 'animation()'

path.animate(
    { transform: "translate(" + newOffset + ",0)" },
    300,
    mina.easeinout,
    animation
  );

**Comment by glynthink** [comment]
ok, got it thanks!
