### ISSUE TITLE
.toDataURL() doesn't keep font-familly attribute

### ISSUE THREAD

**Issue by guenn** [adobe-webplatform/Snap.svg#564]
[script.txt](https://github.com/adobe-webplatform/Snap.svg/files/1361530/script.txt)

The "svg" is drawing with the correct font-family, but the "img" don't.
See result here : http://pictos.kagwalmina.fr/index3.html

Is my code who is wrong or it's a bug ?

Best regards.

**Comment by guenn** [comment]
How i can generate a png file from Snap object with a custom font file ?

**Comment by YonatanHanan** [comment]
Hi,

My solution was to use this site [https://dopiaza.org/tools/datauri/index.php](url) to get the base64 presentation of the font.

and then insert it like this:

`t2.attr({ 'font-size': 80, 'font-family': 'Avenir', fill: '#3D3C3F', 'text-anchor': 'middle' });`

`s.defs.innerHTML = '<style type="text/css">@font-face {font-family: "Avenir"; src: url("data:application/octet-stream;base64,AAEAAAARAQAABAA Long text blablabla");}</style>';`

`document.getElementById('img').src = s.toDataURL();`

and it worked!

**Comment by guenn** [comment]
Thanks a lot. 

It's work !
