### ISSUE TITLE
Memory leak when updating gradients

### ISSUE THREAD

**Issue by Requios** [adobe-webplatform/Snap.svg#565]
A consistent memory leak happens when updating gradients every tick. This makes it pretty much impossible to use dynamic gradients.

Example (keep an eye on the memory and let it run for a while):
https://jsfiddle.net/bgj5veuv/7/

**Comment by ibrierley** [comment]
Hmm you aren't updating an existing gradient though, you are adding a new one each time, so there will be thousands of gradients in the svg defs section. If you want to update the gradient, store a reference to it, and update some attribute of it, rather than using the gradient() method each time.
