### ISSUE TITLE
morphing animation

### ISSUE THREAD

**Issue by 30stomars** [adobe-webplatform/Snap.svg#571]
Hello, I want to make one morphing animation，but the effect is not ideal。

[codepen](https://codepen.io/anon/pen/gXYdNx?editors=1010)

**Comment by ibrierley** [comment]
Not really a lot you can do. Either use a different 2nd path so that the points interpolate better, or use a different morphing library.
If there's a specific bug or something that isn't clear from the original issue then feel free to reopen.
