### ISSUE TITLE
Wrong animation when rotating

### ISSUE THREAD

**Issue by stefanpoeter** [adobe-webplatform/Snap.svg#578]
A simple example

    s.rect(90, 100, 20, 100).animate({ 'transform' : 'r45,100,150'}, 1000)

is doing something very weird. Should simply animate a rotation on the center of the rect, but somehow animates the rotation in a weird kind of way. Found in 0.5.2.

**Comment by ibrierley** [comment]
Are you definitely using 0.5.2 and not 0.5.1 ? My understanding was that this issue (I'm guessing related to https://github.com/adobe-webplatform/Snap.svg/issues/505 ) was fixed for 0.5.2

Could you put up a jsfiddle ?

**Comment by stefanpoeter** [comment]
Sorry, I used the npm package which hosts 0.5.1, also tryied the latest download on the website which I thought was 0.5.2. Do you still ne a jsFiddle?

**Comment by ibrierley** [comment]
Yes, just something testable that shows the problem that folks can see.

**Comment by stefanpoeter** [comment]
Ok, how can I get a hosted snap.svg.js file. The raw link from the repo is delivered as plain text.

**Comment by ibrierley** [comment]
Here's your example on 0.5.2 I just tested.

http://svg.dabbles.info/0.5.2/index.html

I suspect you are still using 0.5.1 even if you think you aren't (check in the snap.svg.js file at the top).

**Comment by stefanpoeter** [comment]
Sorry for the trouble. I just checked the npm registry. The snapsvg module is using the 0.5.1 tag.
