### ISSUE TITLE
Is this repo still active / being maintained please?

### ISSUE THREAD

**Issue by edhenderson** [adobe-webplatform/Snap.svg#586]
Hello. I was wondering if this repo was still being maintained and/or is active? Looks like nothing for over a year? 

Apart from this question, looks fantastic what you guys have put together.

Thank you for sharing.

E.

**Comment by ibrierley** [comment]
There are folk active like myself, but there's not a lot of updates going on. Not sure it needs it though, and most bits can be extended with plugins.

**Comment by behrangsa** [comment]
@ibrierley there are +200 open issues though. Maybe no major new features are needed but what about bugs?

**Comment by gonzalle** [comment]
That is a real issue... There is still many many REAL bugs... 
One must also consider that it is still in 0.X.X...
Maybe one day v.1.X.X would solve those problems...

**Comment by ibrierley** [comment]
What bug are you experiencing ?
