### ISSUE TITLE
Update the Slack invite link

### ISSUE THREAD

**Issue by behrangsa** [adobe-webplatform/Snap.svg#589]
Wanted to join the Slack channel but the [invite link](https://snapsvg.slack.com/shared_invite/MTM2NTE4MTk3MDYwLTE0ODYwODgzNzUtYjQ0YmM1N2U0Mg) was no longer valid.

**Comment by behrangsa** [comment]
My github username @ gmail.

**Comment by mreiche** [comment]
Invite link is still invalid.

**Comment by ibrierley** [comment]
Heya, I don't think anyone uses the Slack channel anymore (shout if anyone does!). I would just post any issues in Github if Snap issue or Stackoverflow if its a general problem.

**Comment by mreiche** [comment]
Ja, looks like the whole project is dead.

**Comment by ibrierley** [comment]
Depends what you mean by the project is dead. There haven't been any updates for a long time, but it's mature enough to use and there's enough knowledge out there to sort most issues. Same with Raphael. If you need something updated with some new requirement, maybe look at svg.js and ask them, as its the only other one I'm aware of really.

**Comment by mreiche** [comment]
I switched to https://svgjs.com/ after struggeling with the documentation and realizing that the last commit is > 3 years old - which pretty means "dead" imho.
