### ISSUE TITLE
stroke colour not changing

### ISSUE THREAD

**Issue by ckalas** [adobe-webplatform/Snap.svg#593]
I am trying to set the stroke colour of a path like so:

```
var path;
path = svg_circle_arc_path(500, 500, 450, -90, val * 180.0 - 90);
arc = svg.path(path)
arc.attr({
    stroke: 'red'
 });
```

But this does nothing. If I set the class and use a css style it colours the stroke, but I can't use this method to colour the path an arbitrary colour at run time.

**Comment by ibrierley** [comment]
Can you put the example on a jsfiddle

**Comment by ckalas** [comment]
[here](https://codepen.io/anon/pen/vjdKZx) is an example from someone else, by adding  `stroke: 'black'` to line 32 of the js part you can see the issue.

**Comment by ckalas** [comment]
when I remove the class from the attribute and add a stroke, I don't see anything drawn.

**Comment by ibrierley** [comment]
You need to put a fiddle up showing the exact problem.

**Comment by ckalas** [comment]
it worked now when I did attrs = { style: "stroke: xxxxx"} instead of attrs = {stroke: xxxx}
