### ISSUE TITLE
Run getbbox on nodejs will always return 0.

### ISSUE THREAD

**Issue by leesc81** [adobe-webplatform/Snap.svg#611]
Is it not supported by nodeJS?

snap.children () [0] .getBBox () or snap.getBBox () will all print out the values shown below.

{ x: 0,
  y: 0,
  width: 0,
  w: 0,
  height: 0,
  h: 0,
  x2: 0,
  y2: 0,
  cx: 0,
  cy: 0,
  r1: 0,
  r2: 0,
  r0: 0,
  path: 
   [ [ 'M', 0, 0 ],
     [ 'l', 0, 0 ],
     [ 'l', 0, 0 ],
     [ 'l', -0, 0 ],
     [ 'z' ],
     toString: [Function: toString] ],
  vb: '0 0 0 0' }

**Comment by DmitryBaranovskiy** [comment]
Snap should be run in the browser environment.
