### ISSUE TITLE
SVG drag and drop - Compatibility issue with recent browsers on mobile (Android) ?

### ISSUE THREAD

**Issue by CelestinHamon** [adobe-webplatform/Snap.svg#618]
Hi everyone!

I'm trying to fix a simple drag and drop feature on a website using snap.svg.
This item works fine on desktops, however it doesn't on Android phones with recent browsers.

It looks like the recent updates of chrome, for example, have broken this feature. When I use an older release, everything works properly as on desktop.

I checked that my problem wasn't related to the phone OS : Two phones on Android 7, one with chrome 64.0.3282 and the other with the 77.0.3865 release, the drag and drop only works on the first one. (I also tried with Samsung browser)

Here is a sample of code which is very similar to the one on my website: 
https://codepen.io/chamon/pen/QWLXYYY
(as you see it's the simplest case)

It has the same problem: works on an old browser but doesn't a recent one.

I would like to know if it's a known and common issue?
And is there any possible fix witch doesn't require removing snap.svg from the project?

Maybe I just missed something on forums. Any help is welcome!

**Comment by ibrierley** [comment]
I suspect you may need to do your own drag handler that accounts for touches or other events these days. See if you can figure which events are created on that mobile browser.

**Comment by CelestinHamon** [comment]
Thanks, you were right! 
Old browsers produce "Touch" events whereas new ones create "TouchEvent" events.
I found how to handle it correctly and modified my code example.

**Comment by ibrierley** [comment]
Great!

If there's a generic fix, it may be worth posting it here, in case others
get the same problem.

**Comment by CelestinHamon** [comment]
All right.

My solution is mostly based on the answer of this topic on stackoverflow. The question is old but the solution is still relevant : https://stackoverflow.com/questions/24739830/how-to-implement-drag-and-drop-in-snap-svg-for-mobile-devices

So I just added few lines on my `move` and `start` functions :

```
var start = function(x, y, ev) {
    if( (typeof x == 'object') && ( x.type == 'touchstart') ) {
        x.preventDefault();
        this.data('ox', x.changedTouches[0].clientX );
        this.data('oy', x.changedTouches[0].clientY );  
    }
    origTransform = this.transform().local;
}
```
```
var move = function(dx, dy, x, y, ev) {
    var clientX, clientY;
    if( (typeof dx == 'object') && ( dx.type == 'touchmove') ) {
       clientX = dx.changedTouches[0].clientX;
       clientY = dx.changedTouches[0].clientY;
       dx = clientX - this.data('ox');
       dy = clientY - this.data('oy');
    }
    this.attr({
      transform: origTransform + (origTransform ? "T" : "t") + [dx, dy]
    });
}
```

Then, I added these three listeners, that also trigger my `start` `stop` and `move` functions:
````
circle.touchstart( start );
circle.touchmove( move );
circle.touchend( stop );
````
