### ISSUE TITLE
It always shows this error 'Cannot set property 'eve' of undefined'

### ISSUE THREAD

**Issue by CherishLiuJunping** [adobe-webplatform/Snap.svg#634]
It always shows this error 'Cannot set property 'eve' of undefined' when I am running my project, after adding the following to my webpack config and ignoring eslint check:
module: {
  rules: [
    {
      test: require.resolve('snapsvg/dist/snap.svg.js'),
      use: 'imports-loader?this=>window,fix=>module.exports=0',
    },
  ],
},
resolve: {
  alias: {
    snapsvg: 'snapsvg/dist/snap.svg.js',
  },
},

**Comment by Alex-Golovin** [comment]
https://www.npmjs.com/package/snapsvg-cjs-ts

**Comment by abid-mujtaba** [comment]
Solved here: https://github.com/adobe-webplatform/Snap.svg/issues/639
