### ISSUE TITLE
Can't make element a link

### ISSUE THREAD

**Issue by tillhoff** [adobe-webplatform/Snap.svg#638]
Please correct (and link) me if this is wrong: It seems there is no possibility to make an element like a rectangle a link to another page. Standard SVG supports this, and it would be great to have the possibility here, too.

**Comment by tillhoff** [comment]
Will close this stale issue - sad you're not developing that product any further.

**Comment by ibrierley** [comment]
I never saw this issue actually. It is possible if you still need it, but will probably need a workaround (there was a recent issue a few days ago about a element).
