### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by ghost** [adobe-webplatform/Snap.svg#71]
In SVG it is possible to do something such as:

<ellipse id="E" cx="90" cy="90" rx="30" ry="40" fill="#448">
<animate attributeName="rx" dur="5s" values="20;90;20" repeatCount="indefinite"/>
<animate attributeName="ry" dur="5s" values="30;60;30" repeatCount="indefinite"/>
</ellipse>

where the animation run continuously.  Cannot get a similar effect out of element.animate.  Thanks

**Comment by zubairanwar2** [comment]
Hmm... I have the same question. @ghost have you figured out the answer yet ? I am having the same question as you.

**Comment by ibrierley** [comment]
You could always create a callback that starts the animation on completion. Or as in the example create a pure markup animation.

**Comment by zubairanwar2** [comment]
ahaan got you, but the markup animation is not supported in all the
browsers.
