### ISSUE TITLE
Snap + AngularJS Directive

### ISSUE THREAD

**Issue by Siyfion** [adobe-webplatform/Snap.svg#72]
In AngularJS all DOM manipulation should be done in directives; thus it is my intention to write a directive that will create the Snap object and perform all the operations on it.

However I'm falling at the first hurdle, getting Snap to create the SVG inside a specific DOM element. My understanding was that I should be able to pass a HTMLElement to the constructor? However the following doesn't seem to work: http://jsfiddle.net/hRy4A/1/

Perhaps I'm being silly somewhere in my code...? Also, it seems that documentation for the `Snap()` constructor is actually missing from the Docs?

**Comment by rbecheras** [comment]
Hi @Siyfion !

Could you share your work about this directive please ?

**Comment by Siyfion** [comment]
Hi @rbecheras, what is it you want to know? Do you want to know what I was working on? Or, just my code, etc?

**Comment by rbecheras** [comment]
I wanted to know your directive code.

But excuse me, I just saw 

> Fixed: http://jsfiddle.net/hRy4A/2/

Thus I know it. I thought your directive was more abstract, but you just perform your specific drawing  instructions into it. Why not.

If you do more, can you share it with us ?

**Comment by Siyfion** [comment]
@rbecheras alas, I had a lot more complex working example, but since then I've switched over to using Meteor and Blaze, so it's all been replaced. However, creating directives to render "objects" was definitely a perfectly workable solution.
