### ISSUE TITLE
Adding a drag handler overwrites the default behavior?

### ISSUE THREAD

**Issue by janmonschke** [adobe-webplatform/Snap.svg#73]
I was trying to attach an onmove event listener to the drag method and expected it to behave like a normal JS event listener, but it seems that when I pass a listener function, the normal drag behavior is overwritten and the element doesn't move anymore.

This fiddle shows what I mean:
http://jsfiddle.net/XLe6N/

The black circle doesn't react to mouse events anymore.

Are we supposed to move the elements ourselves when attaching an onmove listener?

**Comment by TwentyOneSolutions** [comment]
I understand both positions on this matter.

I think that a very simple solution would be that passing `null` will use the default handler, and if someone wants to disable the default handler they can easily pass a function that does nothing.  e.g.:

    obj.drag(null,    // drag behavior works via default, built-in, handler
        function(x, y, evt) { console.log("Drag Started"); },
        function(x, y, evt) { console.log("Drag Ended"); }
    );

vs.

    obj.drag(function(dx, dy, x, y, evt) { /* do nothing, equivalent to current null */ }   // overwrite default handler
        function(x, y, evt) { console.log("Drag Started"); },
        function() { console.log("Drag Ended"); }
    );
