### ISSUE TITLE
.drag() with viewBox set

### ISSUE THREAD

**Issue by Siyfion** [adobe-webplatform/Snap.svg#89]
I'm using the default `Element.drag()` handler with a viewBox applied and it doesn't scale the mouse delta's accordingly, so the drag effect is amplified by 2-3x what it should be, is there an easy way to take the viewBox scaling factor into account?

**Comment by Oliboy50** [comment]
This issue has opened on 31 Oct 2013 and I think it's still a critical issue. 
Is it planned to fix this soon @DmitryBaranovskiy ?

**Comment by jakestmart** [comment]
@DmitryBaranovskiy  also experiencing the same issue +1

**Comment by CyrilSabbagh** [comment]
same issue +1!

**Comment by ibrierley** [comment]
Tried with this... http://svg.dabbles.info/snaptut-dragplugin ?

**Comment by CyrilSabbagh** [comment]
@ibrierley Thanks this works well... :)

**Comment by JeroenWeener** [comment]
I am also experiencing the mentioned issue. The solution of @ibrierley worked like a charm. This isn't very nice behaviour though. +1

**Comment by DmitryBaranovskiy** [comment]
This is not an issue and implemented like this by design.
